version: "2"

services:
  postgres:
    image: "postgres:10.3-alpine"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    env_file:
      - ".env"

  redis:
    image: "redis:4.0-alpine"
    command: redis-server
    volumes:
      - "redis:/data"

  website:
    depends_on:
      - "postgres"
      - "redis"
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"
    env_file:
      - ".env"
    environment:
      DATABASE_URL: postgres://postgres@postgres
      REDIS_URL: redis://redis:6379

volumes:
  redis:
  postgres:
